remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: State of Commercial Banks in India: An Analysis
description: This data story presents insights on the performance and growth of commercial banks in India over the past five years, using data from the Reserve Bank of India. The analysis includes a breakdown of bank branch statistics by state, bank group, and population group, offering a comprehensive view of the Indian banking sector. Visualizations and interactive dashboards are used to illustrate key trends and patterns in the data.
show_downloads: false
github:
  is_project_page: false
